apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ard-audiothek-rss.fullname" . }}-html
  labels:
    {{- include "ard-audiothek-rss.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "ardaudiothek-rss.php").AsConfig | indent 2 }}